version: '2'

services:
  liquidsoap:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.liquidsoap
    volumes:
    - ./liquidsoap/config:/config
    - ./playlists:/playlists
    - ./data:/data
    - /etc/localtime:/etc/localtime:ro
    networks:
    - internal-network
    environment:
    - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
  icecast:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.icecast

    volumes:
      - ./icecast/logs/:/var/log/icecast2
      - ./icecast/config/:/config
      - /etc/localtime:/etc/localtime:ro 
    networks:
      - default
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ICECAST_PASSWORD=${ICECAST_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}
    ports:
    - "8000:8000"
    networks:
    - internal-network

  mopidy:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.mopidy
    volumes:
    - ./mopidy/config:/config
    - ./data/:/data
    - ./playlist:/playlist
    - /etc/localtime:/etc/localtime:ro
    networks:
    - internal-network
    environment:
    - MOPIDY_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - SPOTIFY_USERNAME=${SPOTIFY_USERNAME}
    - SPOTIFY_PASSWORD=${SPOTIFY_PASSWORD}
    - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    
  httpd:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.http
    volumes:
    - ./http/public_html:/usr/local/apache2/htdocs
    environment:
    - WEBRADIO_HOST=${WEBRADIO_HOST}
    - HTTP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
    - "${WEBRADIO_PORT}:80"
    networks:
    - internal-network

networks:
  internal-network:
    external: false
