version: '2'

services:
  liquidsoap:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.liquidsoap
    volumes:
    - ./liquidsoap/config:/config
    - ./liquidsoap/playlists:/playlists
    - ./liquidsoap/data:/data
    #- ./liquidsoap/data:/data
    - /etc/localtime:/etc/localtime:ro
    networks:
    - internal-network
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
 
  icecast:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.icecast

    volumes:
      - ./icecast/logs/:/var/log/icecast2
      - ./icecast/config/:/config
      - /etc/localtime:/etc/localtime:ro 
    networks:
      - default
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_PASSWORD=${ICECAST_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}
    ports:
    - "8000:8000"
    networks:
    - internal-network

  mopidy:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile.mopidy
    volumes:
    - ./mopidy/config:/config
    - /etc/localtime:/etc/localtime:ro
    networks:
    - internal-network
    environment:
    - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - SPOTIFY_USERNAME=${SPOTIFY_USERNAME}
    - SPOTIFY_PASSWORD=${SPOTIFY_PASSWORD}
    - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

networks:
  internal-network:
    external: false
